DROP TABLE IF EXISTS MODEL;

CREATE TABLE MODEL
(
    id   INT AUTO_INCREMENT PRIMARY KEY,
    prog INT,
    curr INT,
    temp double,
    work BOOLEAN DEFAULT false
);

DROP TABLE IF EXISTS BEERMODEL;

CREATE TABLE IF NOT EXISTS BEERMODEL
(
    id   serial PRIMARY KEY,
    temp float
);