DROP TABLE IF EXISTS MODEL;
DROP TABLE IF EXISTS BEERMODEL;

CREATE TABLE MODEL
(
    id   INT PRIMARY KEY,
    prog INT,
    curr INT,
    temp double,
    work BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS BEER_MODEL
(
    id   serial PRIMARY KEY,
    temp float
);